MS.IoT.MarketingPortal.Web/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Azure.ActiveDirectory.GraphClient;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authentication;

namespace MS.IoT.MarketingPortal.Web.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        private readonly ITokenServices tokenServices;

        public UserProfileController(ITokenServices tokenServices)
        {
            this.tokenServices = tokenServices;
        }

        // GET: UserProfile
        public async Task<ActionResult> Index()
        {
            var serviceRoot = new Uri(tokenServices.DirectoryInstance);
            var activeDirectoryClient = new ActiveDirectoryClient(serviceRoot, async () => await tokenServices.GetGraphTokenAsync());

            // use the token for querying the graph to get the user details

            IUser user = await activeDirectoryClient.Me.ExecuteAsync();

            return View(user);
        }

        public ActionResult GrantAccessToNonAdminUsers()
        {
            return Challenge(
                new AuthenticationProperties { Items = { new KeyValuePair<string, string>("IsAdmin", "true")}},
                OpenIdConnectDefaults.AuthenticationScheme);
        }        
    }
}

MS.IoT.MarketingPortal.Web/Views/UserProfile/Index.cshtml
@using Microsoft.Azure.ActiveDirectory.GraphClient
@model User

@{
    ViewBag.Title = "User Profile";
}

<div class="theme-showcase" role="main">
    <div class="container">
        <div class="section">
            <h3>Grant access to all users in your organization</h3><span style="color:crimson"><h5>Only admin can grant access</h5></span>
            <button type="button" onclick="window.location.href='@Url.Action("GrantAccessToNonAdminUsers", "UserProfile")'" class="btn btn-lg btn-primary IoT">Grant Access</button>
            <br />
            <br />
            <h4>User Profile</h4>
            <table class="table table-bordered table-striped">
                <tr>
                    <td>Display Name</td>
                    <td>@Model.DisplayName</td>
                </tr>
                <tr>
                    <td>First Name</td>
                    <td>@Model.GivenName</td>
                </tr>
                <tr>
                    <td>Last Name</td>
                    <td>@Model.Surname</td>
                </tr>
            </table>
        </div>
    </div>
</div>

MS.IoT.MarketingPortal.Web/Views/UserProfile/Relogin.cshtml
@using Microsoft.Azure.ActiveDirectory.GraphClient

@{
    ViewBag.Title = "User Profile";
}
<h2>@ViewBag.Title.</h2>

<p>
    The token for accessing the Graph API has expired.
    Click @Html.ActionLink("here", "RefreshSession", "UserProfile", null, null) to sign-in and get a new access token.
</p>